In [14]:
import pandas as pd
import numpy as np

In [15]:
# Read data and make a copy to manipulate data
df = pd.read_csv('bmw.csv')

In [16]:
data = df.copy()
data.shape

(10781, 9)

In [17]:
# Duplicate data represents 1% of the entire dataset so drop them
data.drop_duplicates(inplace=True)
data.shape

(10664, 9)

In [ ]:
# Select the most important data
columns = ['model','year','mileage','transmission','']

In [51]:
enc_df = pd.get_dummies(data, prefix_sep='_', drop_first=False)
enc_df.head()

,year,price,mileage,tax,mpg,engineSize,model_ 1 Series,model_ 2 Series,model_ 3 Series,model_ 4 Series,...,model_ i3,model_ i8,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,2014,11200,67068,125,57.6,2.0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
1,2018,27000,14827,145,42.8,2.0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
2,2016,16000,62794,160,51.4,3.0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
3,2017,12750,26676,145,72.4,1.5,1,0,0,0,...,0,0,1,0,0,1,0,0,0,0
4,2014,14500,39554,160,50.4,3.0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0

In [64]:
# Correlation matrix of the numerical features to verify intuition
# The price row shows which features are correlated to the price
enc_df.corr().round(2).style.background_gradient(cmap='coolwarm')

In [65]:
# Fuel type, mpg, and tax have little importance so they can be dropped
# mpg and tax are correlated with engine size anyways

cols = ['fuelType','mpg','tax']
final_df = data.drop(columns=cols)
final_df.head()

       model  year  price transmission  mileage  engineSize
0   5 Series  2014  11200    Automatic    67068         2.0
1   6 Series  2018  27000    Automatic    14827         2.0
2   5 Series  2016  16000    Automatic    62794         3.0
3   1 Series  2017  12750    Automatic    26676         1.5
4   7 Series  2014  14500    Automatic    39554         3.0

In [67]:
# Perform dummy encoding on the final dataframe and export as csv
final_df_enc = pd.get_dummies(final_df,prefix_sep='_',drop_first=False)

In [69]:
final_df_enc.to_csv('car_data_good.csv')